Add NewJarManifest function to retrieve MANIFEST from a JAR file
paketo-buildpacks/libjvm pull request #153
Opened 2022-03-15 14:28 UTC by SaschaSchwarze0

## Summary

Adding a function to retrieve the MANIFEST from a JAR file. This is needed in [Support multiple JAR files by picking the first found Main-Class #118](https://github.com/paketo-buildpacks/executable-jar/pull/118)

## Use Cases

See https://github.com/paketo-buildpacks/executable-jar/pull/118

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [x] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

2022-03-16 13:43 UTC, dmikusa-pivotal requested changes
A couple of possible changes. Let me know what you think.

2022-03-16 13:43 UTC, dmikusa-pivotal commented on manifest_test.go
> +		m, err := libjvm.NewJarManifest(filePath)
```suggestion
		m, err := libjvm.NewManifestFromJAR(filePath)
```

2022-03-22 09:32 UTC, SaschaSchwarze0 commented
Thank you for the feedback @dmikusa-pivotal. I applied your suggestions.

2022-03-22 20:03 UTC, dmikusa-pivotal approved these changes

2022-03-22 20:04 UTC, merged